/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    IBiHouses: typeof import('~icons/bi/houses')['default']
    IClarityContractLine: typeof import('~icons/clarity/contract-line')['default']
    IEosIconsThreeDotsLoading: typeof import('~icons/eos-icons/three-dots-loading')['default']
    IIcOutlineMap: typeof import('~icons/ic/outline-map')['default']
    IIcSharpPayment: typeof import('~icons/ic/sharp-payment')['default']
    IIcSharpPhotoSizeSelectSmall: typeof import('~icons/ic/sharp-photo-size-select-small')['default']
    IIcTwotoneBathtub: typeof import('~icons/ic/twotone-bathtub')['default']
    IIcTwotoneBed: typeof import('~icons/ic/twotone-bed')['default']
    IMaterialSymbolsHomeWorkOutline: typeof import('~icons/material-symbols/home-work-outline')['default']
    IMdiArrowDownThick: typeof import('~icons/mdi/arrow-down-thick')['default']
    IMdiArrowUpThick: typeof import('~icons/mdi/arrow-up-thick')['default']
    IMdiBell: typeof import('~icons/mdi/bell')['default']
    IMdiBellOutline: typeof import('~icons/mdi/bell-outline')['default']
    IMdiCalculator: typeof import('~icons/mdi/calculator')['default']
    IMdiChevronLeft: typeof import('~icons/mdi/chevron-left')['default']
    IMdiChevronRight: typeof import('~icons/mdi/chevron-right')['default']
    IMdiClose: typeof import('~icons/mdi/close')['default']
    IMdiContentSaveCheck: typeof import('~icons/mdi/content-save-check')['default']
    IMdiEdit: typeof import('~icons/mdi/edit')['default']
    IMdiFile: typeof import('~icons/mdi/file')['default']
    IMdiFileDocument: typeof import('~icons/mdi/file-document')['default']
    IMdiFileDocumentAlertOutline: typeof import('~icons/mdi/file-document-alert-outline')['default']
    IMdiFileDocumentPlus: typeof import('~icons/mdi/file-document-plus')['default']
    IMdiFilter: typeof import('~icons/mdi/filter')['default']
    IMdiHomeCityOutline: typeof import('~icons/mdi/home-city-outline')['default']
    IMdiMail: typeof import('~icons/mdi/mail')['default']
    IMdiMinus: typeof import('~icons/mdi/minus')['default']
    IMdiMoney: typeof import('~icons/mdi/money')['default']
    IMdiNoteOff: typeof import('~icons/mdi/note-off')['default']
    IMdiPlus: typeof import('~icons/mdi/plus')['default']
    IMdiQuestionMark: typeof import('~icons/mdi/question-mark')['default']
    IMdiSearch: typeof import('~icons/mdi/search')['default']
    IMdiSort: typeof import('~icons/mdi/sort')['default']
    IMdiTrash: typeof import('~icons/mdi/trash')['default']
    IMdiUserOutline: typeof import('~icons/mdi/user-outline')['default']
    IMdiUsers: typeof import('~icons/mdi/users')['default']
  }
}
