services:
  neatrents:
    build:
      args:
        uid: 1000
        TZ: America\New_York
      context: ./
      dockerfile: Dockerfile
    image: neatlancer/neatrents
    container_name: neatrents-app
    restart: unless-stopped
    volumes:
      - ./docker-compose/web/timezone:/etc/timezone
      - ./storage:/var/www/storage
    env_file:
      - .env
    environment:
      AUTORUN_ENABLED: true
      AUTORUN_LARAVEL_MIGRATION_ISOLATION: true
      DB_CONNECTION: mysql
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
  task:
    image: neatlancer/neatrents
    command: ["php", "/var/www/html/artisan", "schedule:work"]
    environment:
      PHP_PFM_POOL_NAME: "neatrents_task"
    depends_on:
      - neatrents
  queue:
    image: neatlancer/neatrents
    command: ["php", "/var/www/html/artisan", "queue:work", "--tries=3"]
    environment:
      PHP_FPM_POOL_NAME: "neatrents_queue"
    depends_on:
      - neatrents